import Head from "next/head";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export function Header() {
  return (
    <div className={[
      styles["top-bar"],
      " h-20 w-full sticky top-0 flex items-center justify-center p-[50px] z-[1]"
    ]}>
      <div className={[
        styles['routes-container'],
        ' w-11/12 flex flex-row justify-between'
      ]}>
        <div className="text-[30px] font-medium text-[#fff]"><Link href="/">LOGO</Link></div>
        <ul className="flex flex-row text-[#fff]">
          <li className="ml-[50px] text-[18px]"><Link href="/">Home</Link></li>
          <li className="ml-[50px] text-[18px]"><Link href="/about">About</Link></li>
          <li className="ml-[50px] text-[18px]"><Link href="/contact">Contact</Link></li>
        </ul>
      </div>
    </div>
  )
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="bg-[url('https://images.pexels.com/photos/842711/pexels-photo-842711.jpeg')] w-full h-full absolute top-0 left-0 bg-no-repeat bg-cover opacity-60 z-0"></div>
        
        
        <Header />

        <div
          className={[
            styles["tex-container"],
            " h-full w-full flex items-center justify-center z-1",
          ]}
        >
          <div className="w-auto h-auto flex flex-col items-center text-[#fff]">
            <h2 className="w-fit text-[90px] font-bold">Hello</h2>
            <p className="text-[25px] font-bold">Wassup bro</p>
          </div>
        </div>

        <div className="h-[1000px]">
          hi
        </div>
        
      </main>
    </>
  );
}
